# Nombre de Redis nodes (1 pour standalone)
redisCluster:
  enabled: true
  name: session-db
  clusterSize: 1

image:
  registry: docker.io
  repository: redis
  tag: "7.0.12"

  # Ports exposés (par défaut 6379)
  service:
    enabled: true
    type: ClusterIP
    port: 6379
    annotations: {}

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  securityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
      add:
        - CHOWN
        - SETGID
        - SETUID
