fullnameOverride: carts-db

architecture: replicaset

auth:
  enabled: false

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: gp2
  accessModes:
    - ReadWriteOnce
  size: 512Mi

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
    add:
      - CHOWN
      - SETGID
      - SETUID

service:
  nameOverride: carts-db
  type: ClusterIP
  port: 27017

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true
